name: FireFox Browser Test Build
on: push
jobs:
  addToCart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #job-1
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:addToCart
      # For generating HTML Reports
      - name: Mochawesome HTML Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - addToCart
          path: cypress/reports/html
      #job-2
  registerFlow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:registerFlow
      # For generating HTML Reports
      - name: Mochawesome HTML Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Register Flow
          path: cypress/reports/html
